version: '3.7'

services:
  app:
    image: charleschrismann/mern:0.0.1
    container_name: mern
    ports:
      - "3000:3333"
    volumes:
      - server_uploads:/app/dist/apps/mern-back/uploads
    networks:
      - mern_net
    environment:
      - MONGO_URL=mongodb://mongodb/my_database
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    container_name: mongodb_container
    ports:
      - "27017:27017"
    networks:
      - mern_net
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
  server_uploads:
networks:
  mern_net:
